name: "CI"
run-name: "${{ github.actor }} - Commit: ${{ github.sha }}"

on:
    push:
        branches: ["main", "develop"]
    pull_request:
        branches: ["main", "develop"]

env:
    PYTHON_VERSION: 3.8
    DJANGO_SETTINGS_MODULE: ./todolist/settings.py

jobs:
    python-ci:
        runs-on: ubuntu-latest

        defaults:
          run:
            working-directory: ./src

        steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Set up Python ${{ env.PYTHON_VERSION }}
          uses: actions/setup-python@v5
          with:
            python-version: '${{ env.PYTHON_VERSION }}'

        - name: Install Dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            pip install flake8 pytest coverage

        - name: Lint
          run: |
            cd ../
            flake8 . --show-source --statistics --exit-zero

        - name: Check Complexity
          run: |
            cd ../
            flake8 . --statistics --max-complexity=10 --exit-zero

        - name: Tests
          run: |
            pytest

        - name: Generate coverage report
          run: pytest --cov-report=xml --cov=.

        - name: Test coverage
          run: pytest -v --cov-report=term-missing --cov=.

        - name: Upload python artifacts
          uses: actions/upload-artifact@v4
          with:
            name: python-artifacts
            path: .
